# Generated by Django 4.2.4 on 2023-08-16 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sector', models.CharField(max_length=60)),
                ('risk_qualifier', models.CharField(choices=[('0', '?'), ('1', 'Aaa'), ('2', 'Aa1'), ('3', 'Aa2'), ('4', 'Aa3'), ('5', 'Baa1'), ('6', 'Baa2'), ('7', 'Baa3')], default='?', max_length=1)),
                ('risk_type', models.CharField(choices=[('0', 'Pendiente'), ('1', 'Riesgo de crédito'), ('2', 'Riesgo de mercado'), ('3', 'Riesgo de liquidez'), ('4', 'Riesgo operativo'), ('5', 'Riesgo regulatorio'), ('6', 'Riesgo de reputación')], default=0, max_length=2)),
                ('risk_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
